### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by Tomo-zou-2525** [7oops4/fleamarket_sample_77d#49]
■ URL
IPアドレス：http://54.95.241.145/
Github（最終課題のリポジトリ）：https://github.com/7oops4/fleamarket_sample_77d

■ Basic認証
ID：admin
Pass：password

■ テスト用アカウント
◯ 購入者用
メールアドレス：buyer@gmail.com
パスワード：buyer00

◯ 購入用カード情報
番号：4242424242424242
期限：02/24 
セキュリティカード：123

◯ 出品者用
メールアドレス：seller00@gmail.com
パスワード：seller00

**Comment by eeee-0000** [comment]
Tomo-zou-2525さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◯すくなくとも3以上の商品が投稿されていない
https://gyazo.com/cbea39815265382ffc8530f59293efb4

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by Tomo-zou-2525** [comment]
eeee-0000様、レビューありがとうございます。
申し訳ありません、商品の方追加しておきました。

再度提出させていただきましたので、ご確認のほどお願いいたします。

**Comment by eeee-0000** [comment]
Tomo-zou-2525さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**

**Comment by Tomo-zou-2525** [comment]
eeee-0000様

無事に通過できたこと嬉しく思います。
コードレビューの方ありがとうございました。
